#!/bin/bash

cd /etc/logcheck/templates

for dir in *; do
  if [[ -d $dir ]]; then
    for file in $dir/*; do
	file=$(basename $file)
	cat definitions $dir/$file |gpp -T|sed '/^\s*$/d' > ../$dir/$file
    done
  fi
done

echo "Testing..."
sudo -u logcheck logcheck -o -t

